services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - egghead
    restart: always
    expose:
      - "3306"
    init: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - egghead
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"
    init: true

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: 
      - .env
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - egghead
    restart: always
    init: true

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/mos/data/wp
      o: bind
  db: 
    driver: local
    driver_opts:
      type: none
      device: /home/mos/data/db
      o: bind

networks:
  egghead:
    driver: bridge