services:
  #---------------------------------------------------
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - my_network
    init: true
    env_file:
      - .env
    restart: always
  #---------------------------------------------------
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wp_files:/var/www/inception/
    networks:
      - my_network
    init: true
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
  #---------------------------------------------------
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - '443:443'
    volumes:
      - wp_files:/var/www/inception/
    networks:
      - my_network
    init: true
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always
  #---------------------------------------------------

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp_files

networks:
  my_network:
    driver: bridge