version: "3.9"

services:
  # Service MariaDB
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  # Service WordPress
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app_network

  # Service NGINX
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app_network

# Configuration des volumes pour la persistance des données
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

# Réseau pour la communication entre les conteneurs
networks:
  app_network:
    driver: bridge
