version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mos/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mos/data/mariadb'

networks:
  inception:
    driver: bridge
